name: "Format and Test on Save"
description: "ファイル保存時に自動フォーマット、リント、テストを実行（学習用）"

# トリガー設定
triggers:
  - type: "file_save"
    patterns:
      - "**/*.ts"
      - "**/*.tsx" 
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.py"

# 実行条件
conditions:
  - type: "file_extension"
    extensions: [".ts", ".tsx", ".js", ".jsx", ".py"]
  - type: "exclude_patterns"
    patterns:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/.next/**"
      - "**/coverage/**"

# 実行ステップ
steps:
  - name: "TypeScript/JavaScript Format & Lint"
    condition: "file.extension in ['.ts', '.tsx', '.js', '.jsx']"
    commands:
      - "npx prettier --write {file_path}"
      - "npx eslint --fix {file_path}"
    description: "Prettierでフォーマット、ESLintで自動修正"

  - name: "Python Format & Lint"  
    condition: "file.extension == '.py'"
    commands:
      - "black {file_path}"
      - "isort {file_path}"
      - "flake8 {file_path}"
    description: "Blackでフォーマット、isortでimport整理、flake8でリント"

  - name: "Run Related Tests"
    condition: "file.path.includes('src/') or file.path.includes('agents/')"
    commands:
      - "npm run test:related {file_path}"
    description: "変更されたファイルに関連するテストを実行"
    timeout: 30
    optional: true

# 学習用設定
learning_features:
  show_explanations: true
  log_commands: true
  highlight_changes: true

# 通知設定
notifications:
  on_success: 
    message: "✅ フォーマット・リント完了: {file_name}"
    duration: 2
  on_error:
    message: "❌ エラーが発生しました: {error_message}"
    duration: 5
    show_details: true