default_agent: magi_agent
agents:
  magi_agent:
    name: magi_agent
    entrypoint: F:/10_code/06_kiro/MAGISystem2/MAGISystem2/agents/magi_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: F:\10_code\06_kiro\MAGISystem2\MAGISystem2\agents
    aws:
      execution_role: arn:aws:iam::262152767881:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-7cbb5d572f
      execution_role_auto_create: false
      account: '262152767881'
      region: ap-northeast-1
      ecr_repository: 262152767881.dkr.ecr.ap-northeast-1.amazonaws.com/bedrock-agentcore-magi_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: magi_agent-4ORNam2cHb
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:262152767881:runtime/magi_agent-4ORNam2cHb
      agent_session_id: 0e270cd5-d684-442e-b232-e6584dcb125a
    codebuild:
      project_name: bedrock-agentcore-magi_agent-builder
      execution_role: arn:aws:iam::262152767881:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-northeast-1-7cbb5d572f
      source_bucket: bedrock-agentcore-codebuild-sources-262152767881-ap-northeast-1
    memory:
      mode: STM_ONLY
      memory_id: magi_agent_mem-XRbpGS7ujQ
      memory_arn: arn:aws:bedrock-agentcore:ap-northeast-1:262152767881:memory/magi_agent_mem-XRbpGS7ujQ
      memory_name: magi_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
