[tool.uv]
# uv configuration for MAGI Decision System

# Python version management
python-preference = "only-managed"
python-downloads = "automatic"

# Package index configuration
index-url = "https://pypi.org/simple"
extra-index-url = []

# Dependency resolution
resolution = "highest"
prerelease = "disallow"

# Virtual environment
venv = ".venv"

# Cache configuration
cache-dir = ".uv-cache"

# Development settings
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.12.0",
    "pytest-cov>=4.1.0",
    "black>=23.12.0",
    "isort>=5.13.0",
    "mypy>=1.8.0",
    "ruff>=0.1.0",
]

# AWS-specific optimizations
[tool.uv.sources]
# Future: Add private package sources if needed
# boto3 = { git = "https://github.com/boto/boto3.git", tag = "1.34.0" }

[tool.uv.environments]
# Environment-specific dependencies
production = [
    "boto3>=1.34.0",
    "opentelemetry-api>=1.21.0",
]

development = [
    "pytest>=7.4.0",
    "black>=23.12.0",
    "ipython>=8.18.0",
]

testing = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
]