import { defineFunction } from '@aws-amplify/backend';

export const bedrockAgentGateway = defineFunction({
  name: 'bedrock-agent-gateway',
  entry: './streaming-handler.ts',
  timeoutSeconds: 600,
  memoryMB: 2048,
  environment: {
    BEDROCK_REGION: 'ap-northeast-1',
    MAGI_AGENT_ID: 'magi_agent-4ORNam2cHb',
    MAGI_AGENT_ALIAS_ID: 'TSTALIASID',
    SOLOMON_SUPERVISOR_AGENT_ID: 'solomon-supervisor-v1',
    SOLOMON_MODEL_ID: 'anthropic.claude-3-opus-20240229-v1:0',
    SOLOMON_TEMPERATURE: '0.4',
    SOLOMON_MAX_TOKENS: '2000',
    CASPAR_AGENT_ID: 'caspar-conservative-v1',
    CASPAR_MODEL_ID: 'anthropic.claude-3-sonnet-20240229-v1:0',
    CASPAR_TEMPERATURE: '0.3',
    CASPAR_MAX_TOKENS: '1500',
    BALTHASAR_AGENT_ID: 'balthasar-innovative-v1',
    BALTHASAR_MODEL_ID: 'anthropic.claude-3-sonnet-20240229-v1:0',
    BALTHASAR_TEMPERATURE: '0.7',
    BALTHASAR_MAX_TOKENS: '1500',
    MELCHIOR_AGENT_ID: 'melchior-balanced-v1',
    MELCHIOR_MODEL_ID: 'anthropic.claude-3-sonnet-20240229-v1:0',
    MELCHIOR_TEMPERATURE: '0.5',
    MELCHIOR_MAX_TOKENS: '1500',
    INLINE_AGENTS_ENABLED: 'true',
    PAYLOAD_REFERENCING_ENABLED: 'true',
    AGENT_ORCHESTRATION_MODE: 'supervisor_delegated',
    OTEL_SERVICE_NAME: 'magi-bedrock-gateway',
    OTEL_EXPORTER_OTLP_ENDPOINT: 'https://api.honeycomb.io',
    LOG_LEVEL: 'INFO',
    AGENT_EXECUTION_TIMEOUT: '120000',
    PARALLEL_EXECUTION_ENABLED: 'true',
    RESPONSE_STREAMING_ENABLED: 'true',
  },
});
